### ISSUE TITLE
Week 4 Activity Ready for Review

### ISSUE THREAD

**Issue by stclassy** [stclassy/groceryListBuilder#2]
@pawaitemadisoncollege 
I chose to do activity 4 in my project so I can get a good start on the code needed. One key learning point is to pay close attention to database layout when inserting data. I had the order of values wrong in my sql so my tests were throwing null pointer exceptions. I'm really enjoying intellij as a development environment. The auto complete functions as well as auto importing is very nice. I know to be careful about auto importing and making sure it's the correct package. The database view is also really nice, especially for building tables. I don't have to spend forever trying to remember what sql I need and worry about proper formatting sql statements.

I got stuck on my sql malformation for a while, I also was having trouble with the log4j2.properties and have it _mostly_ figured out (this had my attention for a while after I figured this out, I was able to address the sql issue pretty quickly). I didn't have hibernate listed as an appender I do now, but I'm having an issue with the property file not recognizing expression language... (maybe I just figured out something?) instead of getting a log folder I get a ${filepath} folder.

**Comment by pawaitemadisoncollege** [comment]
Hi @stclassy! There are a TON of details in this work isn't there?!  Great job figuring so many of them out.  Regarding the ${file path} issue - check out my post in #help from earlier today; I think that'll help you resolve it, but follow up with me if not!

- [ ] Verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertTrue(expectedUser.equals(actualUser));` so that you don't have to compare each instance var/column manually like this: https://github.com/stclassy/groceryListBuilder/blob/f6cc2e6f336d0a383ef84a4fafb2d0f6264ec38b/src/test/java/com/groceryListBuilder/persistence/UserDaoTest.java#L52-L55.
