### ISSUE TITLE
Week 6 Ready for Review

### ISSUE THREAD

**Issue by stclassy** [stclassy/groceryListBuilder#5]
@pawaitemadisoncollege 
Week 6 is ready for review!

I had a lot of issues this week due to changing the naming format of my aws database and forgetting. This was quite a challenge to figure out, but I think I managed to catch a lot of other issues in my code, like my servlet never forwarding the request and response. Other than that, I've been struggling mentally and feel like I'm falling behind. I know I'm at a good point considering I did previous work on my project database so I'm pretty ready for checkpoint 2, I just feel like I'm not doing enough since I'm not hitting 100% of my goals. I'm trying my best to focus on my accomplishments but as the semester goes on I just feel the crunch coming and I'm nervous.

Sorry I know this isn't much of a "What I learned" section

**Comment by pawaitemadisoncollege** [comment]
Hi @stclassy! GREAT job figuring  out the deployment issues!

Regarding the feeling of falling behind: I generally feel if you are within a week of learning a "thing" and implementing the "thing" in your indie project, you are in really good shape. The checkpoints are an additional check to confirm being on target. From my view, you are nailing this!  Project plans should be flexible, since we don't always know what we don't know when building them.  I feel like you've got this!

**Comment by stclassy** [comment]
Thank you for the check in and feedback. Thank helps ease my anxiety a bit.
